package com.gafker.www.mapper;

import com.gafker.www.entity.Pagetest;
import com.gafker.www.entity.PagetestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PagetestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    long countByExample(PagetestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int deleteByExample(PagetestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int insert(Pagetest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int insertSelective(Pagetest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    List<Pagetest> selectByExample(PagetestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    Pagetest selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") Pagetest record, @Param("example") PagetestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int updateByExample(@Param("record") Pagetest record, @Param("example") PagetestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int updateByPrimaryKeySelective(Pagetest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pagetest
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int updateByPrimaryKey(Pagetest record);
}