package com.gafker.www.mapper;

import com.gafker.www.entity.TimesTable;
import com.gafker.www.entity.TimesTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TimesTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wo_timestable
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int deleteByExample(TimesTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wo_timestable
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wo_timestable
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int insert(TimesTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wo_timestable
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int insertSelective(TimesTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wo_timestable
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    List<TimesTable> selectByExample(TimesTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wo_timestable
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    TimesTable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wo_timestable
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int updateByExampleSelective(@Param("record") TimesTable record, @Param("example") TimesTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wo_timestable
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int updateByExample(@Param("record") TimesTable record, @Param("example") TimesTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wo_timestable
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int updateByPrimaryKeySelective(TimesTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wo_timestable
     *
     * @mbg.generated Mon Oct 16 22:30:02 CST 2017
     */
    int updateByPrimaryKey(TimesTable record);
}